### ISSUE TITLE
Persistent messages folder

### ISSUE THREAD

**Issue by mathewvp** [rabbitmq/amqp091-go#27] opened 2021-12-01 09:44 UTC
Hi,

When writing persistent messages using this library, the messages are being written to "queues" folder but while using php amqp library, it is being written to "msg_store_persistent" folder. Where is this configuration being set? This is not an issue with the library but I need help to figure this out, thanks.

**Comment by lukebakken** [comment] 2021-12-01 14:31
Could you please provide a minimal set of code I can run in each language to observe what you report?

Also, always let us know the following information when reporting an issue:
* Erlang and RabbitMQ version
* Operating systems and version
* Go version and Go client library version
* PHP version and php-amqplib version

**Comment by lukebakken** [comment] 2021-12-01 14:32
I see you've also opened this issue - https://github.com/php-amqplib/php-amqplib/issues/962

Please, we can't assist without a way to reproduce. What you're asking us to do now is write code and guess what you are doing. Since we're providing free support, we can't assist if you don't help us out a bit. Thanks for understanding.

**Comment by mathewvp** [comment] 2021-12-01 15:32
Php code

`$exchange = new \AMQPExchange($this->_channel);
$exchange->setName('xxx.push-notification.exg');
$exchange->setType(AMQP_EX_TYPE_DIRECT);
$exchange->setFlags(AMQP_DURABLE);
// declare method deprecated. ref http://php.net/manual/fa/amqpexchange.declare.php
$exchange->declareExchange();
$this->_exchange = $exchange;

$queue = new \AMQPQueue($this->_channel);
$queue->setName('xxx.push-notification.que');
$queue->setFlags(AMQP_DURABLE);
$args = array('x-ha-policy' => 'all');
if ($hasDeadLetter) {
    $args['x-dead-letter-exchange'] = 'xxx.err.exg';
    $args['x-dead-letter-routing-key'] = $queueName;
}
$queue->setArguments($args);
$queue->declareQueue();
$queue->bind('xxx.push-notification.exg', $routingKey);

$params = array('content_type' => 'text/json', 'delivery_mode'=>2);
$exchange->publish($msg, $routingKey, false, $params);`

Golang code

`conn, err := amqp.Dial(fmt.Sprintf("amqp://%s:%s@%s:%s/", "guest", "guest", "xx.xx.xx.xx", "5672"))
if err != nil {
    fmt.Println(err)
    return
}

ch, err := conn.Channel()
if err != nil {
    fmt.Println(err)
    return
}



out = []byte(`{"command":"sendPushNotification","data":{"userId":"0","profileId":"2701","message":"xxx xxx xxx","section":"general","extraParams":[{"key":"img","val":"aHR0cHM6Ly9zdGWLm00bWFycnkuaW4vdWkvaW1hZ2VzL2xvZ28uZGVza3RvcE5vdGlmaWNhdGlvbi5wbmc="},{"key":"webUrl","val":"https:\/\/lens.xxx.in\/click?evt_id=14d9edf5-7268-463e-8141-03aacf536e65&evt_nm=Clicked+Desktop+Notification&evt_typ=generic&app_id=xxx-jobs&eml_sub=&usr_did=2701&cpg_sc=&cpg_md=&cpg_nm=&cpg_cnt=&cpg_tm=&link_txt=expo+notification+link+clicked&em_type=&cpg_subcode=2021-11-25&cpg_dt=&url=https%3A%2F%2Fstag-fe.xxx.in%2Fsubscription%2FchoosePackage%3Futm_source%3D%26utm_medium%3D%26utm_campaign%3D%26utm_content%3D%26utm_term%3D%26utm_subcode%3D2021-11-25%26evt_typ%3Dgeneric"}],"customFields":[{"key":"pixelTrackerUrl","val":"https:\/\/lens.xxx.in\/i?evt_id=60b675c8-f16d-4224-b3c1-a0b92dccb011&evt_nm=Viewed+Desktop+Notification&evt_typ=generic&app_id=xxx-jobs&eml_sub=&usr_did=2701&cpg_sc=&cpg_md=&cpg_nm=&cpg_cnt=&cpg_tm=&link_txt=&em_type=&cpg_subcode=2021-11-25&cpg_dt="},{"key":"title","val":"xxx team is here in xxx!"}]}}`)

err = ch.Publish("xxx.push-notification.exg", "*", false, false, amqp.Publishing{
    ContentType:  "text/json",
    Body:         out,
    DeliveryMode: amqp.Persistent,
})
`

same payload used in both cases.

**Comment by mathewvp** [comment] 2021-12-01 15:42
versions

amqp: 1.10.2

PHP 7.0.33-50+ubuntu20.04.1+deb.sury.org+1 (cli) (built: May  1 2021 11:50:22) ( NTS )

go version go1.13.4 darwin/amd64 (binary is cross compiled for linux)

github.com/rabbitmq/amqp091-go v1.2.0

**Comment by lukebakken** [comment] 2021-12-01 22:11
Thanks for the information. I have created a repository with your code and added you as a collaborator here:

https://github.com/lukebakken/amqp091-go-gh-27

The code you provided, while useful, is incomplete and does not run out-of-the box. I shouldn't have to spend time getting your code running when I could be spending time diagnosing your issue. In this case I will continue updating the https://github.com/lukebakken/amqp091-go-gh-27 repository with what I consider to be a _minimum runnable example_ that I will use in the future as a reference for when people ask for assistance.

For what it's worth, RabbitMQ 3.7.14 has been out of support for a while now. I will be testing using RabbitMQ 3.9.10 and Erlang 24.1.7m

**Comment by michaelklishin** [comment] 2021-12-02 06:22
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(

**Closed** 2021-12-02 06:22 UTC
